import os

from ESXi_config import create_config_file
from ESXi_config import generate_random_string
from ESXi_config import create_symlinks


def create_esx_bin(base_path=os.path.join(os.path.expanduser("~"), "ESXI 7","bin")):
    bin_file = {
        # "[": 45,
        # "[[": 4,
        #"ash": 86,
        "amldump": 86,
        "apiForwarder": 454786,
        "apply-host-profiles": 4763,
        "applyHostProfile": 964,
        "applyHostProfileWrapper": 964,
        "authd": 964,
        "auto-backup": 964,
        "backup-check.sh": 964,
        "backup.sh": 964,
        "BootModuleConfig.sh": 964,
        "chardevlogger": 964,
        "check_serial": 964,
        "chkconfig": 964,
        "cim_host_powerops": 964,
        "cim-diagnostic.sh": 964,
        "cmmds-tool": 964,
        "crx-cli": 964,
        "crypto-util": 964,
        "dcbd": 964,
        "dcui": 964,
        "dcuiweasel": 964,
        "df": 964,
        "dhclient-uw": 964,
        "dmesg": 45,
        "doat": 248,
        "dosfsck": 14,
        "enum_instances": 426,
        "esxcfg-advcfg": 64,
        "esxcfg-dumppart": 913,
        "esxcfg-info": 28,
        "esxcfg-init": 46,
        "esxcfg-ipsec": 123,
        "esxcfg-module": 486,
        "mpath": 746,
        "esxcli.py": 964,
        "esxhpcli": 54,
        "esxhpedit": 524,
        "esxupdate": 456,
        "firmwareConfig.py": 964,
        "generate-certificates": 426,
        "getAccessToken": 123,
        "grabCIMData": 453,
        "host_reboot.sh": 530,
        "host_shutdown.sh": 264,
        "hostd-probe.sh": 432,
        "init-launcher": 44,
        "initSystemStorage": 145,
        "initterm.sh": 1768,
        "install": 34,
        "lldpnetmap": 43,
        "loadESXEnable": 176,
        "lockfile": 425,
        "netdbg.py": 2351,
        "nologin": 453,
        "pmemGC": 453,
        "powerOffVms": 12,
        "schedsnapshot": 335,
        "services.sh": 452,
        "sharedStorageHostProfile.sh": 52,
        "shutdown.sh": 12,
        "slpd": 954,
        "smartd": 921,
        "sntp": 453,
        "storageRM": 454,
        "summarize-dvfilter": 243,
        "techsupport.sh": 453,
        "tmpwatch.py": 475,
        "vm-support": 452,
        "vmfs-support": 452,
        "vmfsfilelockinfo": 4,
        "VmfsLatencyStats.py": 964,
        "vmware-autostart.sh": 94,
        "vmware-vimdump": 64,
        "vmx": 58,
        "vmx-buildtype": 96,
        "vprobe": 527,
        "watchdog.sh": 964,
    }
    for name, size in bin_file.items():
        create_config_file(base_path,name,generate_random_string(size))

    my_symlinks = {
        "[": "/usr/lib/vmware/busybox/bin/busybox",
        "[[": "/usr/lib/vmware/busybox/bin/busybox",
        "amldumpp": "/bin/vmkvsitools",
        "ash": "/usr/lib/vmware/busybox/bin/busybox",
        "awk": "/usr/lib/vmware/busybox/bin/busybox",
        "basename": "/usr/lib/vmware/busybox/bin/busybox",
        "bootOption": "/bin/vmkvsitools",
        "bunzip2": "/usr/lib/vmware/busybox/bin/busybox",
        "bzip2": "/usr/lib/vmware/busybox/bin/busybox",
        "cat": "/usr/lib/vmware/busybox/bin/busybox",
        "chgrp": "/usr/lib/vmware/busybox/bin/busybox",
        "chmod": "/usr/lib/vmware/busybox/bin/busybox",
        "chown": "/usr/lib/vmware/busybox/bin/busybox",
        "chvt": "/usr/lib/vmware/busybox/bin/busybox",
        "cksum": "/usr/lib/vmware/busybox/bin/busybox",
        "clear": "/usr/lib/vmware/busybox/bin/busybox",
        "configstorecli": "/usr/lib/vmware/configmanager/bin/configstorecli",
        "cp": "/usr/lib/vmware/busybox/bin/busybox",
        "crond": "/usr/lib/vmware/busybox/bin/busybox",
        "cut": "/usr/lib/vmware/busybox/bin/busybox",
        "date": "/usr/lib/vmware/busybox/bin/busybox",
        "dd": "/usr/lib/vmware/busybox/bin/busybox",
        "diff": "/usr/lib/vmware/busybox/bin/busybox",
        "dirname": "/usr/lib/vmware/busybox/bin/busybox",
        "dnsdomainname": "/usr/lib/vmware/busybox/bin/busybox",
        "du": "/usr/lib/vmware/busybox/bin/busybox",
        "echo": "/usr/lib/vmware/busybox/bin/busybox",
        "egrep": "/usr/lib/vmware/busybox/bin/busybox",
        "eject": "/usr/lib/vmware/busybox/bin/busybox",
        "env": "/usr/lib/vmware/busybox/bin/busybox",
        "esxcli": "/bin/esxcli.py",
        "expr": "/usr/lib/vmware/busybox/bin/busybox",
        "false": "/usr/lib/vmware/busybox/bin/busybox",
        "fgrep": "/usr/lib/vmware/busybox/bin/busybox",
        "find": "/usr/lib/vmware/busybox/bin/busybox",
        "getty": "/usr/lib/vmware/busybox/bin/busybox",
        "grep": "/usr/lib/vmware/busybox/bin/busybox",
        "gstorecli": "/usr/lib/vmware/gstorecli/bin/gstorecli",
        "gunzip": "/usr/lib/vmware/busybox/bin/busybox",
        "gzip": "/usr/lib/vmware/busybox/bin/busybox",
        "halt": "/usr/lib/vmware/busybox/bin/busybox",
        "head": "/usr/lib/vmware/busybox/bin/busybox",
        "hexdump": "/usr/lib/vmware/busybox/bin/busybox",
        "hostname": "/usr/lib/vmware/busybox/bin/busybox",
        "hwclock": "/bin/vmkvsitools",
        "pgrep": "/bin/vmkvsitools",
        "pidof": "/bin/vmkvsitools",
        "pkill": "/bin/vmkvsitools",
        "vmware": "/bin/vmkvsitools",
        "vdu": "/bin/vmkvsitools",
        "vdf": "/bin/vmkvsitools",
        "uptime": "/bin/vmkvsitools",
        "rpcfg": "/bin/vmkvsitools",
        "pigz": " /usr/lib/vmware/pigz/bin/pigz",
        "ping": " /bin/vmkping",
        "ping6": " /usr/lib/vmware/pigz/bin/pigz",
        "inetd": "/usr/lib/vmware/busybox/bin/busybox",
        "init": "/usr/lib/vmware/busybox/bin/busybox",
        "irqinfo": "/bin/vmkvsitools",
        "kill": "/usr/lib/vmware/busybox/bin/busybox",
        "ln": "/usr/lib/vmware/busybox/bin/busybox",
        "logger": "/usr/lib/vmware/busybox/bin/busybox",
        "login": "/usr/lib/vmware/busybox/bin/busybox",
        "ls": "/usr/lib/vmware/busybox/bin/busybox",
        "lsacpi": "/bin/vmkvsitools",
        "lsof": "/bin/vmkvsitools",
        "lspci": "/bin/vmkvsitools",
        "lzop": "/usr/lib/vmware/busybox/bin/busybox",
        "lzopcat": "/usr/lib/vmware/busybox/bin/busybox",
        "md5sum": "/usr/lib/vmware/busybox/bin/busybox",
        "mcopy": "/bin/mtools",
        "mdir": "/bin/mtools",
        "mmd": "/bin/mtools",
        "netdbg": "/bin/netdbg.py",
        "mkdir": "/usr/lib/vmware/busybox/bin/busybox",
        "mkfifo": "/usr/lib/vmware/busybox/bin/busybox",
        "mknod": "/usr/lib/vmware/busybox/bin/busybox",
        "mktemp": "/usr/lib/vmware/busybox/bin/busybox",
        "more": "/usr/lib/vmware/busybox/bin/busybox",
        "mv": "/usr/lib/vmware/busybox/bin/busybox",
        "nohup": "/usr/lib/vmware/busybox/bin/busybox",
        "nslookup": "/usr/lib/vmware/busybox/bin/busybox",
        "od": "/usr/lib/vmware/busybox/bin/busybox",
        "passwd": "/usr/lib/vmware/auth/bin/passwd",
        "poweroff": "/usr/lib/vmware/busybox/bin/busybox",
        "printf": "/usr/lib/vmware/busybox/bin/busybox",
        "python": "/bin/python3",
        "python3": "python3.8",
        "python3.5": "/bin/python3",
        "rm": "/usr/lib/vmware/busybox/bin/busybox",
        "rmdir": "/usr/lib/vmware/busybox/bin/busybox",
        "runInRP": "/usr/lib/vmware/rp/bin/runInRP",
        "scp": "/usr/lib/vmware/busybox/bin/scp",
        "sed": "/usr/lib/vmware/busybox/bin/busybox",
        "seq": "/usr/lib/vmware/busybox/bin/busybox",
        "setsid": "/usr/lib/vmware/busybox/bin/busybox",
        "sh": "/usr/lib/vmware/busybox/bin/busybox",
        "sha1sum": "/usr/lib/vmware/busybox/bin/busybox",
        "sha256sum": "/usr/lib/vmware/busybox/bin/busybox",
        "sha512sum": "/usr/lib/vmware/busybox/bin/busybox",
        "sleep": "/usr/lib/vmware/busybox/bin/busybox",
        "sort": "/usr/lib/vmware/busybox/bin/busybox",
        "ssh": "/usr/lib/vmware/openssh/bin/ssh",
        "ssl_client": "/usr/lib/vmware/busybox/bin/busybox",
        "slat": "/usr/lib/vmware/busybox/bin/busybox",
        "stty": "/usr/lib/vmware/busybox/bin/busybox",
        "sum": "/usr/lib/vmware/busybox/bin/busybox",
        "sync": "/usr/lib/vmware/busybox/bin/busybox",
        "tail": "/usr/lib/vmware/busybox/bin/busybox",
        "tar": "/usr/lib/vmware/busybox/bin/busybox",
        "taskset": "/usr/lib/vmware/busybox/bin/busybox",
        "tee": "/usr/lib/vmware/busybox/bin/busybox",
        "test": "/usr/lib/vmware/busybox/bin/busybox",
        "time": "/usr/lib/vmware/busybox/bin/busybox",
        "timeout": "/usr/lib/vmware/busybox/bin/busybox",
        "true": "/usr/lib/vmware/busybox/bin/busybox",
        "uname": "/usr/lib/vmware/busybox/bin/busybox",
        "uniq": "/usr/lib/vmware/busybox/bin/busybox",
        "unlzop": "/usr/lib/vmware/busybox/bin/busybox",
        "unzip": "/usr/lib/vmware/busybox/bin/busybox",
        "usleep": "/usr/lib/vmware/busybox/bin/busybox",
        "vim-cmd": "/bin/hostd",
        "vi": "/usr/lib/vmware/busybox/bin/busybox",
        "watch": "/usr/lib/vmware/busybox/bin/busybox",
        "wc": "/usr/lib/vmware/busybox/bin/busybox",
        "wget": "/usr/lib/vmware/busybox/bin/busybox",
        "which": "/usr/lib/vmware/busybox/bin/busybox",
        "who": "/usr/lib/vmware/busybox/bin/busybox",
        "xargs": "/usr/lib/vmware/busybox/bin/busybox",
        "zcat": "/usr/lib/vmware/busybox/bin/busybox",
    }

    create_symlinks(base_path,my_symlinks)

